ALTER TABLE pagos 
    MODIFY COLUMN nombre_tarjeta VARCHAR(255) NOT NULL,
    MODIFY COLUMN numero_tarjeta VARCHAR(255) NOT NULL,
    MODIFY COLUMN fecha_expiracion VARCHAR(255) NOT NULL,
    MODIFY COLUMN cvv VARCHAR(255) NOT NULL;